### ISSUE TITLE
$MOR Pricing Model Inclusion 

### ISSUE THREAD

**Issue by EnergyHound** [MorpheusAIs/Morpheus#152]
Tagging an issue here that popped up during conversation regarding issuance incentives and potential pricing models. 

Might be helpful to create a model that shows an effective price being paid for the token based on an assumed amount of Ethereum staked. Pool assumptions etc.

A model that looks at it from the perspective of various capital profiles. 

Existing DAO governances looking for additional beta on their treasury yields
Current OG ETH stakers (@tetranode types) 
VC varieties (both small 7 mil with higher risk profiles and larger more established firms)
Degen (Scott from PR etc)
Crypto Native, OG etc. would help each pool visualize how $Mor fits in their respective desired outcomes

cc @DavidAJohnston

**Comment by DavidAJohnston** [comment]
Seems that a community member has created a website to make many of these estimates.
https://morstats.info/
