### ISSUE TITLE
Walkthrough - Submit code | Submit ETH Address for Contribution Rewards.md

### ISSUE THREAD

**Issue by EnergyHound** [MorpheusAIs/Morpheus#242]
cc: @DavidAJohnston 

This walkthrough serves as a guide and process for submitting work 

In this walkthrough we will show you
1) How to do a code contribution 
2) How to Submit an ETH address and “proof of contribution”

We will be using the repo at - [https://github.com/MorpheusAIs/Morpheus]

To Contribute to MorpheusAIs and get credit you'll need 3 things. 
1) A Github Account
2) An ETH address
3) A contribution to the project that is approved for developer weights. 

Notes: If you need to get up to speed on using Github or creating an account you can check out [https://youtu.be/iv8rSLsi1xo?si=35G6p5rCaLeiIgsl]

----

In this example we’re going to contribute to submit a review of the smart contract code with notations. 

1) We navigate to the appropriate file that we’re going to contribute and click “edit”  
2) We enter in the notes (Note we end the title with .md to ensure that its set up in Github as a plain text document file)
3) We click "commit changes"

<img width="1510" alt="Screenshot 2024-01-05 at 11 25 33 PM" src="https://github.com/MorpheusAIs/Morpheus/assets/124720530/f336ca19-5fc0-47e1-97e0-495ffc9e354d">

After the Contributions have been added and we’ve committed the changes we’re then going to do a pull request to request submitted for approval.

We click on the big green button - “create pull request”

<img width="1202" alt="Screenshot 2024-01-05 at 11 31 47 PM" src="https://github.com/MorpheusAIs/Morpheus/assets/124720530/f3f872a5-509d-4a7c-b3e8-3f4752b2f458">

As part of the pull request we will be asked to share any relevant information or notes.  We added some brief notes referencing test reports, who was involved, and we shared an ETH address that should receive credit. 

<img width="1291" alt="Update TestingReports #239" src="https://github.com/MorpheusAIs/Morpheus/assets/124720530/68abb9d3-49dd-463c-bf46-fcfedbd865ce">

We now save the GitHub link where our work report was saved. We will use this when submitting a Proof of Work Claim in the Github account. 

In this case the link that contains the work is - [https://github.com/MorpheusAIs/Morpheus/blob/main/TestingReports.md]

We then navigate to the “Code - Proof of Contribution” section shown below since our work had to do with the code base. [https://github.com/MorpheusAIs/Morpheus/blob/main/Code%20-%20Proof_Of_Contribution.md]

<img width="1504" alt="Screenshot 2024-01-05 at 11 49 48 PM" src="https://github.com/MorpheusAIs/Morpheus/assets/124720530/a90af76b-3f88-45bc-b346-43ebd6f60869">

After we’ve clicked on Code - Proof of Contribution we will then edit the this document and do a pull request after submitting the appropriate proof/description of work and the ETH address to which the work should be credited.

<img width="1252" alt="Screenshot 2024-01-05 at 11 55 48 PM" src="https://github.com/MorpheusAIs/Morpheus/assets/124720530/b5fea768-718d-4a5d-a966-066764c969e4">

We click “edit in place” and scroll to the bottom of the page to add the wallet address and a link to the work as shown below. (This is where we add the link that we saved above. 

<img width="1546" alt="Screenshot 2024-01-06 at 12 10 51 AM" src="https://github.com/MorpheusAIs/Morpheus/assets/124720530/f3255e8e-581a-474c-b1fd-05590cb8615e">

Then we scroll to the top of the page and click “commit changes”. 

A pop up box then appears asking for notes and an extended description. We add the Extended description and then click. “Propose changes”

<img width="437" alt="Propose changes" src="https://github.com/MorpheusAIs/Morpheus/assets/124720530/eabd6b5f-c9bd-4f51-a57f-cf5614b2b266">

On the next page we will be shown the description that we submitted and a quick snapshot of the changes that we made as displayed below. 

<img width="1550" alt="Screenshot 2024-01-06 at 12 18 25 AM" src="https://github.com/MorpheusAIs/Morpheus/assets/124720530/c722d6bd-b593-4219-80ac-badb1f562bd1">

We then click on “Create Pull Request”

The next page again displays the description and the changes we made. 

<img width="1400" alt="Screenshot 2024-01-06 at 12 21 27 AM" src="https://github.com/MorpheusAIs/Morpheus/assets/124720530/1ef3174a-778a-4e08-a750-1627142c51a6">

We click on “create pull request” again and are then shown the commits that are in queue. 

We now wait for the approval or denial by the reviewers with “write” access. 

<img width="1363" alt="Screenshot 2024-01-06 at 12 23 45 AM" src="https://github.com/MorpheusAIs/Morpheus/assets/124720530/9f70953a-df08-46ea-b180-59d82e6e9872">

Congratulations on your submittal.

**Comment by DavidAJohnston** [comment]
Thanks. I believe this has been addressed.
