### ISSUE TITLE
Separation of "Withdraw" and "Claim" Function

### ISSUE THREAD

**Issue by EnergyHound** [MorpheusAIs/Morpheus#271]
WE may consider separating the "claim MOR" function from the "withdraw stETH" function so that users can remove stETH while still allowing MOR to remain unclaimed. 

Here the stETH was withdrawn at which point $MOR was automatically claimed simultaneously. 

https://goerli.etherscan.io/tx/0xadd6183f6e63a1dc4341c3174de877c6ee54a5973da6bea82b67bf55bc2e6ecd 

<img width="1389" alt="Screenshot 2024-01-11 at 3 14 14 PM" src="https://github.com/MorpheusAIs/Morpheus/assets/124720530/703b905c-10d0-4c8e-bb95-3f116e6e238f">

cc @DavidAJohnston

**Comment by DavidAJohnston** [comment]
This can been addressed and resolved in the Smart Contract code.
