### ISSUE TITLE
Issue with minting function on stETH

### ISSUE THREAD

**Issue by Tigerbuidl** [MorpheusAIs/Morpheus#278]
I went through the instructions step by step my first problem was the pictures Every picture I tried to open took me to a page that said "Sorry this is not the page you are looking for", the second problem I had was with stETH I minted my SepoliaETH but no stETH was deposited to the wallet as referenced in the following photos. I tried three times
 
![Screenshot 2024-01-12 at 11 32 12 AM](https://github.com/MorpheusAIs/Morpheus/assets/156273774/6ecc083f-7627-49a2-9d0a-8a61be49c54d)

![PNG image](https://github.com/MorpheusAIs/Morpheus/assets/156273774/cada6f55-4bdf-44a5-a891-54455f3580b2)

![PNG image](https://github.com/MorpheusAIs/Morpheus/assets/156273774/d45ab826-da65-469d-bc82-26e090491c7a)

**Comment by DavidAJohnston** [comment]
Noted. I believe this has been resolved. Thanks.

**Comment by Tigerbuidl** [comment]
yes I think it was resolved thank you for your help
