### ISSUE TITLE
"shift + return" submits chat

### ISSUE THREAD

**Issue by Bougey** [MorpheusAIs/Morpheus#294]
This issue is found in the main chat box of the app when communicating with Morpheus:

Normally in editors you can either hit "shift + return" or just "return" to begin a new line of typing. (like I'm doing here)

The chat box does not allow this. I end up sending partial responses because I am unable to create a new line.

Should be an easy fix.

**Comment by betterbrand** [comment]
which browser, os?

**Comment by Bougey** [comment]
It's on the actual app that's installed - 0.0.5

MacBook Pro M2
Sonoma 14.0

**Comment by Qiwi2681** [comment]
The behavior is implemented in /ui/index.html

**Comment by betterbrand** [comment]
Now I see. That is is part of an old ui that was used prior to 005. It needs to be removed as soon as functionalities are duplicated into the new ui, which is in /src.

**Comment by DavidAJohnston** [comment]
Sure. Lets close this issue. Thanks guys.
