### ISSUE TITLE
Why does the code have yarn and package-lock both?

### ISSUE THREAD

**Issue by YashKumarVerma** [MorpheusAIs/Morpheus#555]
Why does the project have both package-lock and yarn.lock?

1. Confusion and maintenance overhead to keep both in sync.
2. Potential inconsistencies in dependency versions between Yarn and npm.
3. Confusions for new contributors

**Comment by dnovacik** [comment]
My bet would be this is because a bad .gitgnore file :)

**Comment by betterbrand** [comment]
It needs to go.
