### ISSUE TITLE
Robust UI components with Next.js 

### ISSUE THREAD

**Issue by creeping-vampires** [MorpheusAIs/Morpheus#633]
I have some idea for UI components.

Current UI folder is using very basic vanilla js setup and it will be difficult to add more complex functionality in app going further.

I can convert this into a next.js setup with cleaner UI components and APIs .

This will help the project to add more functionality faster in the UI .

@DavidAJohnston let me know if I can proceed with this ?

**Comment by dannweeeee** [comment]
I am interested in contributing to the next.js setup if you were to proceed! lmk ser 🫡

**Comment by betterbrand** [comment]
Please review the node repo. A lot has been added. UI still needs attention though

**Comment by creeping-vampires** [comment]
Sure, I will look into it
